language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
before_script:
  - psql -c "CREATE ROLE fast_food with createdb login password 'fast_food'" postgres
  - psql -c "CREATE DATABASE fast_food_fast_prod owner fast_food" postgres
  - python3 manage.py create_db
script: 
  - nosetests --with-coverage --cover-package=app
  - coveralls
branches:
  except:
  - master
  - develop
  - ft-user-views-160296771
  - ft-order-views-160237681
  - ft-data-models-160237610
  - ch-unittest-160237591
  - ch-environment-and-structure-160237646
  only:
  - challenge2
  - ft-menu-inventory-160543586
  - ft-order-history-160532780
  - ft-menu-inventory-160543586
  - bg-bugs-and-refactoring-160621108
  - develop
  - ch-code-linting-160773903
after_success:
 - coveralls
notifications:
  slack:
    on_success: never
    on_failure: never
  email: false